[SFG] pushing 53 route and CloudFront integration

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -1,6 +1,3 @@
-# .github/workflows/deploy.yml
-#
-
 name: Deploy Website
 
 on:
@@ -11,10 +8,8 @@ jobs:
   deploy:
     runs-on: ubuntu-latest
     steps:
-      # Step 1: Check out the code
       - uses: actions/checkout@v2
 
-      # Step 2: Configure AWS credentials
       - name: Configure AWS credentials
         uses: aws-actions/configure-aws-credentials@v1
         with:
@@ -22,33 +17,34 @@ jobs:
           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
           aws-region: eu-west-1  
 
-      # Step 3: Setup Terraformm
       - name: Setup Terraform
         uses: hashicorp/setup-terraform@v1
 
-      # Step 4: Build step (if you have any build requirements)
       - name: Build website
         run: |
           echo "next step"
 
-      # Step 5: Deploy infrastructure
       - name: Deploy infrastructure
         working-directory: ./infrastructure
         run: |
           terraform init
           terraform apply -auto-approve
 
-      # Step 6: Sync website files to S3
       - name: Sync files to S3
         run: |
-            aws s3 sync ./website s3://personal-resume-website-tatofs
+          aws s3 sync ./website s3://personal-resume-website-tatofs
             
       - name: Invalidate CloudFront cache
+        working-directory: ./infrastructure  
         run: |
-            distribution_id=$(terraform output -raw cloudfront_distribution_id)
-            aws cloudfront create-invalidation --distribution-id $distribution_id --paths "/index.html"
+          DIST_ID=$(terraform output -raw cloudfront_distribution_id)
+          if [ -n "$DIST_ID" ]; then
+            aws cloudfront create-invalidation --distribution-id $DIST_ID --paths "/*"
+          else
+            echo "Failed to get CloudFront distribution ID"
+            exit 1
+          fi
         
-      # Add Cypress smoke tests here
       - name: Run Cypress tests
         run: |
-            echo "No Cypress tests added yet"
+          echo "No Cypress tests added yet"
