[SFG] pushing 53 route and CloudFront integration

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -7,11 +7,6 @@ on:
 jobs:
   deploy:
     runs-on: ubuntu-latest
-    
-    env:
-      AWS_REGION: eu-west-1
-      S3_BUCKET: personal-resume-website-tatofs
-      
     steps:
       - uses: actions/checkout@v2
 
@@ -20,7 +15,7 @@ jobs:
         with:
           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-          aws-region: ${{ env.AWS_REGION }}
+          aws-region: eu-west-1  
 
       - name: Setup Terraform
         uses: hashicorp/setup-terraform@v1
@@ -33,31 +28,29 @@ jobs:
         working-directory: ./infrastructure
         run: |
           terraform init
-          terraform apply -auto-approve -replace="aws_cloudfront_distribution.website" -replace="aws_route53_zone.website"
+          terraform apply -auto-approve
 
       - name: Sync files to S3
         run: |
-          aws s3 sync ./website s3://${{ env.S3_BUCKET }}
-
+          aws s3 sync ./website s3://personal-resume-website-tatofs
+            
       - name: Get CloudFront Distribution ID
-        id: get-cloudfront-distribution-id
         working-directory: ./infrastructure
+        id: cloudfront
         run: |
-          DIST_ID=$(terraform output -raw cloudfront_distribution_id)
-          echo "CLOUDFRONT_DISTRIBUTION_ID=$DIST_ID" >> $GITHUB_ENV
+            DIST_ID=$(terraform output -raw cloudfront_distribution_id)
+            echo "::set-output name=distribution_id::$DIST_ID"
         
-
       - name: Invalidate CloudFront Cache
         run: |
-          if [ -n "$CLOUDFRONT_DISTRIBUTION_ID" ]; then
-            aws cloudfront create-invalidation --distribution-id "$CLOUDFRONT_DISTRIBUTION_ID" --paths "/*"
-          else
-            echo "Failed to get CloudFront distribution ID"
-            exit 1
-          fi
-        env:
-          CLOUDFRONT_DISTRIBUTION_ID: ${{ env.CLOUDFRONT_DISTRIBUTION_ID }}
-
+            DIST_ID=${{ steps.cloudfront.outputs.distribution_id }}
+            if [ -n "$DIST_ID" ]; then
+              aws cloudfront create-invalidation --distribution-id $DIST_ID --paths "/*"
+            else
+              echo "Failed to get CloudFront distribution ID"
+              exit 1
+            fi
+        
       - name: Run Cypress tests
         run: |
           echo "No Cypress tests added yet"
